name: Publish to PyPI
on:
  workflow_dispatch:
    inputs:
      pypi_repo:
        description: "Repo to upload to (TestPyPI or PyPI)"
        default: "testpypi"
        required: true

jobs:
  build_wheels:
    name: Build wheel for on cp${{ matrix.python }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        include:
          # manylinux builds
          - os: ubuntu-latest
            python: "36"
            platform: manylinux_x86_64
          - os: ubuntu-latest
            python: "37"
            platform: manylinux_x86_64
          - os: ubuntu-latest
            python: "38"
            platform: manylinux_x86_64

          # macos builds
          - os: macos-latest
            python: "38"
            platform: macosx_x86_64

          # Windows builds
          - os: windows-2019
            python: "36"
            platform: win_amd64
          - os: windows-2019
            python: "37"
            platform: win_amd64
          - os: windows-2019
            python: "38"
            platform: win_amd64

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.3
        env:
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform }}
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BUILD_VERBOSITY: 3
          CIBW_BEFORE_TEST: pip install -r {project}/requirements-dev.txt
          CIBW_TEST_COMMAND: pytest -sv {project}/tests

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build sdist
        run: python setup.py sdist

      - name: Download wheels
        with:
          name: wheels
          path: dist

      - name: Show files to upload
        shell: bash
        run: ls -la dist

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
        if: ${{ github.event.inputs.pypi_repo == 'testpypi' }}

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
        if: ${{ github.event.inputs.pypi_repo == 'pypi' }}
